"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = exports.basePath = exports.FORMATWEBP = exports.FORMATSVG = exports.FORMATPNG = exports.FORMATJPG = void 0;
const getImgSrc = (path, filename, format) => {
  /*  sunknudsen. (2020, Mar 27). How to use static media assets generated by CRA’s npm build in SSR mode?. StackOverflow.
   *  https://stackoverflow.com/questions/60874394/how-to-use-static-media-assets-generated-by-cra-s-npm-build-in-ssr-mode
   */
  const basePath = `${process.env.PUBLIC_URL}/images`;
  // const basePath = `static/images`;

  return `${basePath}${path}/${filename}.${format}`;
};
const basePath = exports.basePath = '/static/images';
const FORMATWEBP = exports.FORMATWEBP = 'webp';
const FORMATSVG = exports.FORMATSVG = 'svg';
const FORMATPNG = exports.FORMATPNG = 'png';
const FORMATJPG = exports.FORMATJPG = 'jpg';
var _default = exports.default = getImgSrc;